### ISSUE TITLE
Message not pre filling in android device

### ISSUE THREAD

**Issue by anoopmm** [tkporter/react-native-sms#26] opened 2017-09-15 16:35 UTC
#18

**Comment by tkporter** [comment] 2017-09-28 23:45
I haven't had the opportunity to reproduce this, is it happening with a specific device? It seems pretty undesirable to not have the message body be shown (even if pressing "send" still sends the pre-filled message)

**Comment by rlyshw** [comment] 2017-11-27 22:20
Confirmed on my emulator running Nexus 5X API 25, 7.1.1 (Google Play), x86.

Basically the same as #18 except pressing SEND doesn't do anything, there is no "hidden" text in the input box or anything.

**Comment by fredrikp** [comment] 2018-01-08 12:21
@tkporter: I have this problem also. Android 7.1.1 running on a Nexus 6. Using the standard Android "Messages" app. The input field for message text is empty with a placeholder ("Type an SMS message"). The send button is disabled.

It turns out that the solution to this is to not only send the body like this:
sendIntent.putExtra("sms_body", body);
but also like this:
sendIntent.putExtra(sendIntent.EXTRA_TEXT, body);
Ref. https://developer.android.com/training/sharing/send.html

I have made a pull request with this change: https://github.com/tkporter/react-native-sms/pull/43

**Comment by tkporter** [comment] 2018-01-12 01:52
Closing this after #43 and will republish under version 1.5.2 later today. Feel free to reopen if this issue continues!

**Closed by tkporter** 2018-01-12 01:52 UTC
